# Generated by Django 4.2.13 on 2024-06-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='temp',
        ),
    ]
