# Generated by Django 4.2.13 on 2024-06-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_temp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='temp',
            new_name='user',
        ),
    ]
